name: 'QA Workflow'

on:
  push:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:
  use-ci-workflow:
    uses: ./github/workflow/ci.yaml
    with:
      input: 'CI workflow is finished'
