name: 'CI Workflow'

on:
  push:
    branches:
      - ci

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    uses: .github/workflows/build.yaml

  test:
    name: '[2] Test Larevel App'
    runs-on: ubuntu-latest
    needs: [build]
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test

    steps:
      - name: '[2.1] Setup PHP with PECL extension'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: '[2.2] Checkout'
        uses: actions/checkout@v4

      - name: 'Restore the Cache'
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./vendor
          key: '${{ github.sha }}-php-vendor-cache'

      - name: 'Install Composer if Cache not Found'
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          composer install

      - name: '[2.4] Setup Environmental Variables'
        run: |
          cp .env.ci .env
          cp .env.ci .env.testing

      - name: '[2.5] Generate Key & Build the Application'
        run: |
          php artisan key:generate

      - name: '[2.6] Migrate the Database'
        run: |
          php artisan migrate

      - name: '[2.7] Run Unit Testing'
        run: |
          php artisan test
